//baseURL: ""
languageCode: "en-us"
title: "Abid KP"

googleanalytics: G-0P6EWLPFP0
disqusShortname: 
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  //tag: "tags"
  //category: "categories"

enableEmoji: true
params:
  version: 3

  favicon: "/images/fav.png"
  //description: "A high performance hugo theme for personal portfolio and blog."

  # Navbar Menus
  customMenus:
  # home
  disable_home: false
  profile_image: "/images/avatar2.jpg"
  name: "Muhammed Abid KP"
  profession: "Programmer | Designer | Freelancer"
  github: "https://github.com/abidkakkur11"
  linkedin: "https://linkedin.com/in/abidkp"
  twitter: "https://twitter.com/Abidkkr"
  instagram: "https://instagram.com/aabye__"
  facebook: "https://www.facebook.com/abid.kakkur"

  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm Abid KP, A Tech Enthusiast, Designer As well as..!I have been involving in the area of IT since last 5 years. From my school periods
onwards.I started my research and self-studying in programming. I got many
opportunities to participate and showcase my skills in different competition and
events.
"
  descripe_l2_person: "Check out my blogs [here](https://abidkp.wordpress.com)"
  skills:
    - name: C
      percentage: 80
    - name: Python
      percentage: 75
    - name: OOP
      percentage: 80
    - name: Graphic Design
      percentage: 80

  # Experience
  disable_experience: true
  experience:
    - company: "Google"
      role: "Software developer"
      startdate: Feb 2021
      enddate: present
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Facebook"
      role: "Fullstack developer"
      startdate: Mar 2020
      enddate: Dec 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Amazon"
      role: "Fullstack developer"
      startdate: Feb 2019
      enddate: Jan 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.

  # Education
  disable_education: false
  education:
    - degree: "Diploma"
      branch: "Computer Engineering"
      university: "GOVERNMENT POLYTECHNIC COLLEGE,MEPADI"
      startedyear: "2018"
      graduation: "2021"
    - degree: "B.Tech(Drop Out)"
      branch: "Computer Engineering"
      university: "KNS INSTITUTE OF TECHNOLOGY,BANGALORE"
      startedyear: "2015"
      graduation: "2017"
    - degree: "Plus Two"
      branch: "Science"
      university: "Nanminda HSS"
      startedyear: "2013"
      graduation: "2015"

  # Projects
  disable_projects: false
  projects:

  # Achievements
  disable_achievements: false
  achievements:
    - title: Digital Skills Hackathone
      description: Won digital skills hackathon conducted by Tinkerhub & Ilab.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you..!
  email: "abidkakkur11@gmail.com"

  # Footer
  socialiconfooter: true
  recentposts: false

  # Blog
  showdescription: false
  tweet: false
